# Generated by Django 6.0.4 on 2026-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('ingresos', models.FloatField()),
                ('deudas', models.FloatField()),
                ('tiene_empleo', models.BooleanField()),
                ('condicion_salud', models.CharField(choices=[('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
